### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/gitbook-plugin-theme-cornerstone#3]
For us to be able to consume this in our GitBook docs, this repo needs to be published to npm as `gitbook-plugin-theme-cornerstone`

@swederik can you knock this out? Or switch our NPM stuff to be org based so I don't have to ping/pester you to do stuff like this? (:

**Comment by swederik** [comment]
We should move this to @cornerstone/gitbook-plugin-theme or something.

**Comment by dannyrb** [comment]
@swederik create an issue
